# Labgrid Exporter Configuration Template
# This file is used as a template - variables are replaced at runtime
# by the entrypoint.sh script based on environment variables.
#
# Environment variables:
#   DUT_HOST - Hostname of the DUT container
#   DUT_PORT - TCP port for serial-over-TCP (default: 5000)
#   EXPORTER_NAME - Name of this exporter

# Template markers will be replaced:
# __DUT_HOST__ -> DUT_HOST environment variable
# __DUT_PORT__ -> DUT_PORT environment variable  
# __EXPORTER_NAME__ -> EXPORTER_NAME environment variable

__EXPORTER_NAME__:
  NetworkSerialPort:
    host: "__DUT_HOST__"
    port: __DUT_PORT__
    speed: 115200
